name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ] # main に push されたら自動デプロイ
  workflow_dispatch:   # 手動実行も可能

permissions:
  contents: read
  pages: write           # GitHub Pages への書き込み権限
  id-token: write        # デプロイ時の OIDC 用

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # 安定版でビルド

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Build web
        # GitHub Pages（プロジェクトページ）配下で動くように base-href を設定（repo名に合わせる）
        run: flutter build web --release --base-href /shima_kouiki_homepage4/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web # ビルド成果物を Pages 用アーティファクトに

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        # GitHub Pages にデプロイ（Settings > Pages の Source: GitHub Actions を利用）
        uses: actions/deploy-pages@v4


